import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";
import FooterComponent from "@/components/FooterComponent"
import CarouselComponent from "@/components/CarouselComponent";
import SliderComponent from "@/components/SliderComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComponent/>
        <CarouselComponent/>
        <SliderComponent/>
        <div className="pt-[80px]">
        {children}
        <FooterComponent/>
        </div>
        </body>
    </html>
  );
}
